title: Expensive Lines
email: ""
description: >-
  Draw expensive lines together on the blockchain. Drawer of the most lines
  gets the artwork's NFT.
baseurl: ""
url: "https://expensivelines.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nahurst
github_username:  nahurst

# Build settings
# theme: minima
plugins:
  - jekyll-postcss
  - jekyll-environment-variables

sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - cypress
  - cypress.json
  - postcss.config.json
  - tailwind.config.js